In [ ]:
#!pip install numpy

In [ ]:
#! pip install pandas

In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4]
print(l*3)
l=[1,'ABC',True]
print(type(l))

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
<class 'list'>


In [ ]:
b=np.array([1,2,3,4,5,6])
a=np.array([1,2,3,4])
print(a.dtype)
print(a)
print(a*3)
print(a)
print(a+10)

int32
[1 2 3 4]
[ 3  6  9 12]
[1 2 3 4]
[11 12 13 14]


In [ ]:
print(l)
l=np.array(l)
l

[1, 'ABC', True]


array(['1', 'ABC', 'True'], dtype='<U11')

In [ ]:
#l*3

In [ ]:
a=np.array([1,2,3,4,5,6,7])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5 6 7]
(7,)
1


In [ ]:
a_2=np.array([[1,2],[3,4],[5,6]])
print(a_2)
print(a_2.shape)
print(a_2.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2


In [ ]:
a_z=np.zeros((3,4))
print(a_z)
print(a_z.shape)
print(a_z.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
2


In [ ]:
a_n=np.random.random((3,4))
print(a_n)
print(a_n.shape)
print(a_n.ndim)

[[0.63793799 0.22752952 0.97392913 0.25836064]
 [0.00414726 0.1516091  0.74960093 0.57777637]
 [0.27352527 0.85947061 0.79893667 0.5446056 ]]
(3, 4)
2


In [ ]:
a_l=np.linspace(0,100,10)
print(a_l)
print(a_l.shape)
print(a_l.ndim)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
(10,)
1


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.size)
print(a.T)

(2, 3)
6
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
print(a)
print(a.shape)
b=a.reshape(3,2)
print("\n\n",b)
print(b.shape)
c=a.reshape(6,1)
print("\n\n",c)
print(c.shape)
d=a.reshape(1,6)
print("\n\n",d)
print(d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


 [[1 2]
 [3 4]
 [5 6]]
(3, 2)


 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


 [[1 2 3 4 5 6]]
(1, 6)


In [ ]:
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print(a)
b=np.array([7,8,9,10,11,12]).reshape(2,3)
print(b)
c=np.concatenate((a,b),axis=0)
print(c)
print(c.shape)
print(c.ndim)
d=np.concatenate((a,b),axis=1)
print(d)
print(d.shape)
print(d.ndim)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
2
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)
2


In [ ]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
f=np.array([[1,2,3],[4,5,6]],dtype='float')
print(f)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
t=np.array((1,2,3))
t

array([1, 2, 3])

In [ ]:
t=np.append(t,[4,5,6,7,8])

In [ ]:
t

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
t=np.insert(t,2,[10,11,12,13])
t


array([ 1,  2, 10, 11, 12, 13,  3,  4,  5,  6,  7,  8])

In [ ]:
t=np.delete(t,[2,3,4,5])
t

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [ ]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
a[-1]

9

In [ ]:
a[2:4]

array([5, 7])

In [ ]:
a=np.arange(20,30).reshape(5,2)
a

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
a[2,1]

25

In [ ]:
f=a.flatten()
print(f.shape)
print(f)


(10,)
[20 21 22 23 24 25 26 27 28 29]


In [ ]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
a[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=a+10
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
a/2

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
10>14

False

In [ ]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
cond=a>15
a[cond]

array([16, 17, 18, 19, 20])

In [ ]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
a>15

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [1]:
import numpy as np

In [2]:
names=np.array(["Harry","Tom","Bob","Harry","Harry"])
names

array(['Harry', 'Tom', 'Bob', 'Harry', 'Harry'], dtype='<U5')

In [ ]:
c=names=="Harry"
names[c]

array(['Harry', 'Harry', 'Harry'], dtype='<U5')

In [ ]:
c=names!='Harry'
names[c]

array(['Tom', 'Bob'], dtype='<U5')

In [22]:
names=np.array(["Harry","Tom","Bob","Harry","Harry","Jerry","John","Abhishek","RohAN","Amit","Satvika Madam"])
names

array(['Harry', 'Tom', 'Bob', 'Harry', 'Harry', 'Jerry', 'John',
       'Abhishek', 'RohAN', 'Amit', 'Satvika Madam'], dtype='<U13')

In [23]:
cond1=names=='Tom'
cond2=names=='Jerry'
names[cond1|cond2]

array(['Tom', 'Jerry'], dtype='<U13')

In [24]:
names[(names=='Tom')|(names=='Jerry')]

array(['Tom', 'Jerry'], dtype='<U13')

In [25]:
names[(names=='Tom')|(names=='Jerry')]='Rahul'

In [26]:
names

array(['Harry', 'Rahul', 'Bob', 'Harry', 'Harry', 'Rahul', 'John',
       'Abhishek', 'RohAN', 'Amit', 'Satvika Madam'], dtype='<U13')

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.sum(a))
print(np.prod(a))

3.5
1.707825127659933
2.9166666666666665
21
720


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.max())
print("Max elements row-wise : ",arr.max(axis=1))
print(arr.sum())
print(arr.cumsum())

9
Max elements row-wise :  [3 6 9]
45
[ 1  3  6 10 15 21 28 36 45]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(a+b)
print(a.dot(b))
print(a*b)

[[2 4]
 [6 8]]
[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]
